config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /rs/ do
    devise_for :users
    root to: 'pages#home'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :posts, only: [:new, :index, :show, :edit]
    post '/posts/new', to: 'posts#create', as: 'create'
    get '/profile', to: 'pages#profile', as: 'profile'
    get '/myposts', to: 'pages#myposts', as: 'myposts'
    patch ':id/change_status', to: 'pages#change_status', as: 'change_status'
    patch ":id/update", to: "posts#update", as: 'update_post'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :load_date, :load_c, :unload_c, :truck_type, :load_city, :unload_city, :load_address, :unload_address, :weight, :length, presence: true
  validate :load_date_cannot_be_in_the_past, on: :create
  scope :filter_by_load_c, -> (load_c) { where load_c: load_c }
  scope :filter_by_unload_c, -> (unload_c) { where unload_c: unload_c }
  scope :filter_by_truck_type, -> (truck_type) { where("'#{truck_type}' = ANY (truck_type)") }
  scope :filter_by_load_date, -> (load_date) { where load_date: load_date.to_date }

  def load_date_cannot_be_in_the_past
    if load_date.present? && load_date < Date.today
      errors.add(:load_date, "can't be in the past")
    end
  end

  def hours_ago
    h_ago = (Time.now - self.created_at) / 3600
    if h_ago < 1
      "#{(h_ago * 60).round} minutes ago"
    elsif h_ago > 24
      "#{(h_ago / 24).round} days ago"
    else
      "#{h_ago.round} hours ago"
    end
  end

  def reference
    "#{self.id.to_s.last}#{self.user.id.to_s.last}#{self.load_c.first(2)}#{self.unload_c.first(2)}#{Date.today.strftime('%d')}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :posts, dependent: :destroy

  validates :terms, acceptance: true

  def profile_incomplete?
    self.company_name.nil? || self.company_name == ""
    self.first_name.nil? || self.first_name == ""
    self.last_name.nil? || self.last_name == ""
    self.coc.nil? || self.coc == ""
    self.vat.nil? || self.vat == ""
    self.company_address.nil? || self.company_address == ""
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  around_action :switch_locale
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  after_action :verify_authorized, only: :edit, unless: :skip_pundit?
  before_action :authenticate_user!, except: [ :home ]
  before_action :complete_profile, only: [:show, :new], if: :user_signed_in?
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
  end

  def complete_profile
    if current_user.profile_incomplete?
      flash[:alert] = t('complete_profile')
      redirect_to(edit_user_registration_path)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:terms])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :company_address, :last_name, :company_name, :coc, :vat, :mobile_nr])
  end

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  private

  # def profile_incomplete?
  #   current_user.company_name.nil? || current_user.company_name == ""
  #   current_user.first_name.nil? || current_user.first_name == ""
  #   current_user.last_name.nil? || current_user.last_name == ""
  #   current_user.coc.nil? || current_user.coc == ""
  #   current_user.vat.nil? || current_user.vat == ""
  #   current_user.company_address.nil? || current_user.company_address == ""
  # end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    filter
  end

  def profile
    @user = current_user
  end

  def myposts
    @posts = Post.where(user: current_user).paginate(:page => params[:page], per_page: 12).order(created_at: :desc)
    filter
  end

  def filter
    filtering_params(params).each do |key, value|
      @posts = @posts.public_send("filter_by_#{key}", value) if value.present?
    end
  end

  def change_status
    @post = Post.find(params[:id])
    @post.update!(status: false)
    redirect_to post_path(@post), flash: {notice: "Staus changed!"}
  end

  def verify
  end

  private

  # A list of the param names that can be used for filtering the Posts list
  def filtering_params(params)
    params.slice(:load_date, :load_c, :unload_c, :truck_type)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @my_posts = Post.where(id: Post.group(:load_c, :unload_c, :truck_type, :load_city, :weight, :length, :description).select("min(id)"),user_id: current_user.id).paginate(:page => params[:page], per_page: 4)
    repost
    @countries = ["AL - Albania", "AD - Andorra", "AM - Armenia", "AT - Austria", "AZ - Azerbaijan", "BA - Bosnia and Herzegovina", "BE - Belgium", "BG - Bulgaria", "BY - Belarus", "CH - Switzerland", "CY - Cyprus", "CZ - Czech Republic", "DE - Germany", "DK - Denmark", "EE - Estonia", "ES - Spain", "FI - Finland", "FR - France", "GE - Georgia", "GR - Greece", "HR - Croatia", "HU - Hungary", "IE - Ireland", "IS - Iceland", "IT - Italy", "LV - Latvia", "LI - Liechtenstein", "LT - Lithuania", "LU - Luxembourg", "MK - Macedonia", "MD - Moldova", "ME - Montenegro", "NL - Netherlands", "NO - Norway", "PL - Poland", "PT - Portugal", "RO - Romania", "RS - Serbia", "RU - Russia", "SE - Sweden", "SI - Slovenia", "SK - Slovakia", "TR - Turkey", "UA - Ukraine", "UK - United Kingdom", "XK - Kosovo"]
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.status = true
    if @post.save
      redirect_to myposts_path, notice: "Post created"
    else
      # render :new not working
      redirect_to new_post_path, notice: I18n.t('mandatory_fields')
    end
  end

  def index
    @posts = Post.where(status: true).paginate(:page => params[:page], per_page: 10).order(created_at: :desc)
    filter
  end


  def show
    repost
    @post = Post.find(params[:id])
    # display user
    @user = User.find(@post.user_id)
    @posts_count = Post.where(user_id: @user.id).count
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.save
      redirect_to post_path(@post), notice: "Post updated"
    else
      render :new
    end
    authorize @post
  end

  def filter
    filtering_params(params).each do |key, value|
      @posts = @posts.public_send("filter_by_#{key}", value) if value.present?
    end
  end

  def repost
    if params[:repost].present?
      @post = Post.new(load_c: params[:repost][:load_c], load_city: params[:repost][:load_city], load_address: params[:repost][:load_address], unload_c: params[:repost][:unload_c], unload_city: params[:repost][:unload_city], unload_address: params[:repost][:unload_address], length: params[:repost][:length], weight: params[:repost][:weight], description: params[:repost][:description], truck_type: params[:repost][:truck_type], price: params[:repost][:price])
    else
      @post = Post.new
    end
  end

  private

  def post_params
    params.require(:post).permit(:load_date, :unload_date, :load_time, :unload_time, :length, :weight, :load_address, :unload_address, :description, {truck_type: []}, :adr, :price, :load_city, :unload_city, :load_c, :unload_c)
  end

  def filtering_params(params)
    params.slice(:load_date, :load_c, :unload_c, :truck_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cargster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('logoo.png') %>

  </head>
  <body>

    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>

      <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container">

  <div class="pt-4">

    <% if user_signed_in? %>

    <h2 class="text-center fancy my-4" id=""><%= t('hello') %></h2>
    <div class="d-none d-lg-block pt-0" style="padding-bottom: 0.015rem;">
      <%= form_tag posts_path, method: :get, class: "row gx-2 my-2" do %>
      <%= render "/shared/filter" %>
      <% end %>
    </div>
    <div class="d-lg-none">
      <%= link_to posts_path, class: "btn btn-lg bg-white text-primary shadow-sm w-100 mb-3" do %>
        <i class="fa fa-sm fa-solid fa-cube"></i> <%= I18n.t('freight_overview') %></i>
      <% end %>
      <%= link_to myposts_path, class: "btn btn-lg bg-white text-primary shadow-sm w-100 mb-3" do %>
        <i class="fa fa-solid fa-list"></i> <%= I18n.t('my_posts') %>
      <% end %>
      <%= link_to profile_path, class: "btn btn-lg bg-white text-primary shadow-sm w-100 mb-3" do %>
        <i class="fa fa-solid fa-user"></i><i class="fas fa-brands fa-whatsapp"></i> <%= I18n.t('account') %>
      <% end %>
      <%= link_to new_post_path, class: "btn btn-lg btn-primary shadow-sm text-white mb-3 w-100" do %>
        <i class="fa fa-sm fa-solid fa-plus"></i> <%= I18n.t('create_new') %>
      <% end %>
    </div>


    <% else %>
    <%# user not signed in ? %>

      <h2 class="text-center fancy my-4" id="home_header"><%= t('hello') %></h2>
      <h5 class="lead text-center text-muted mb-3"><strong><%= t('value_prop') %></strong></h5>
      <div class="text-center mt-5">
        <%= link_to t('register'), new_user_registration_path, class: "rounded-4 px-5 btn btn-lg btn-primary text-white" %>
      </div>

    <% end %>
  </div>
</div>
<%= render "/shared/switch_locale" %>
<%= render "/shared/footer" %>

app/views/pages/myposts.html.erb
<div class="container">
  <div class="">
    <div class="d-lg-none mt-2 d-flex align-items-center justify-content-between">
      <h5 class="m-3"><%= t('my-posts') %></h5>
      <a href="#myCollapse" class="btn text-primary m-3" data-bs-toggle="collapse"><i class="bi bi-funnel"></i> <%= t('filter') %></a>
    </div>
    <%= form_tag myposts_path, method: :get, class: "collapse mb-3 show row gx-2", id:"myCollapse" do %>
    <%= render "/shared/filter" %>
    <% end %>
    <% if current_user.posts.count == 0 %>
    <div class="my-5">
    <p class="text-center text muted">You havent posted yet <span><%= link_to I18n.t('create_new'), new_post_path, class: "text-primary"%></span></p>
    </div>

    <% else %>
    <% @posts.each do |post| %>
    <div class="col-lg-12 gx-2">
    <%= link_to post_path(post) do %>
      <%= render '/shared/post', post: post %>
    <% end %>
    </div>
    <% end %>
    <% end %>
    <div class="my-3 d-flex justify-content-center">
    <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="bg-white my-2 rounded p-3">
    <%= simple_form_for(@post, method: :patch, url: update_post_path, multipart: true) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <div class="row">
        <div class="col-lg-6">
          <div class="row">
            <div class="col-6">
              <%= f.input :load_c, label: "Loading", prompt: "Country", collection: @countries %>
            </div>
            <div class="col-6">
              <%= f.input :load_city, label: "City", placeholder: "ZIP and Place" %>
            </div>
          </div>
          <%= f.input :load_address, label: "Loading address", placeholder: "Full address" %>

          <div class="row">
            <div class="col-6">
              <%= f.input :load_date, as: :date, html5: true, label: "Loading date" %>
            </div>
            <div class="col-6">
              <%= f.input :load_time, as: :time, html5: true, label: "Loading time" %>
            </div>
          </div>

        </div>
        <div class="col-lg-6">
          <div class="row">
            <div class="col-6">
              <%= f.input :unload_c, label: "Unloading", prompt: "Country", collection: @countries %>
            </div>
            <div class="col-6">
              <%= f.input :unload_city, label: "City", placeholder: "ZIP and Place" %>
            </div>
          </div>
          <%= f.input :unload_address, label: "Unloading address", placeholder: "Full address" %>
          <div class="row">
            <div class="col-6">
              <%= f.input :unload_date, as: :date, html5: true, label: "Unloading date" %>
            </div>
            <div class="col-6">
              <%= f.input :unload_time, as: :time, html5: true, label: "Unloading time" %>
            </div>
          </div>

        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <div class="row">
            <div class="col-6">
              <%= f.input :truck_type, label: "Truck type", prompt: "Truck type", collection: ["Tautliner", "Tandem", "Frigo", "Platform", "Combi"] %>
            </div>
            <div class="col-6">
              <%= f.input :adr, label: "ADR"%>
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="row">
            <div class="col-6">
              <%= f.input :weight, label: "Weight", placeholder: "meters" %>
            </div>
            <div class="col-6">
              <%= f.input :length, label: "Length", placeholder: "tons" %>
            </div>
          </div>
        </div>
      </div>
      <%= f.input :description, label: "Description", placeholder: "More details about the post" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Update", class: "btn btn-primary text-white w-100" %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">

  <div class="d-lg-none mt-2 d-flex align-items-center justify-content-between">
  <h5 class="m-3"><%= @posts.count %> <%= t('search-freight') %></h5>
  <a href="#myCollapse" class="btn text-primary m-3" data-bs-toggle="collapse"><i class="bi bi-funnel"></i> <%= t('filter') %></a>
  </div>
  <%= form_tag posts_path, method: :get, class: "collapse show mb-3 row gx-2", id:"myCollapse" do %>

  <%= render "/shared/filter" %>

  <% end %>


  <% unless @posts.count == 0 %>
    <% @posts.each do |post| %>
      <div class="col-lg-12 gx-2">
        <%= link_to post_path(post) do %>
        <%= render "/shared/post", post: post %>
        <% end %>
      <% end %>
    <% else %>
    <p class="text-center mt-5"><%= t('void') %></p>
    <%= image_tag "void.svg", class: "rounded mx-auto d-block mt-3", style: "height: 33vh; width: 50%;" %>
  <% end %>

  <div class="my-3 d-flex justify-content-center">
    <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>

  </div>

</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row flex-row-reverse gx-3  mb-4">
    <%# PATTERNS %>

    <div class="col-sm-4" style="overflow: hidden;" >
      <p class="d-none d-lg-block px-3 my-3 text-muted"><%= t('suggestions') %></p>

      <div class="d-lg-none mt-2 d-flex align-items-center justify-content-between">
      <h5 class="m-3"><%= t('create_new_l') %></h5>
      <a href="#myCollapse" class="btn text-primary m-3" data-bs-toggle="collapse"><i class="bi bi-lightning"></i> <%= t('suggestions') %></a>
    </div>
    <div class="collapse show" id="myCollapse">
    <%= render "/shared/suggestions" %>
    </div>


    </div>
    <%# CREATE POST FORM %>
    <div class="col-sm-8">
    <p class="d-none d-lg-block px-3 my-3 text-muted"><%= t('create_new_l') %></p>
    <div class="bg-white rounded p-4">
      <%= simple_form_for(@post, method: :post, url: create_path, multipart: true) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <div class="row">
          <div class="col-lg-6">
            <div class="row">
              <div class="col-6">
                <%= f.input :load_c, label: I18n.t('load'), input_html: { class: 'select2' }, prompt: I18n.t('country'), collection: @countries %>
              </div>
              <div class="col-6">
                <%= f.input :load_city, label: I18n.t('city'), placeholder: I18n.t('zip_and_place') %>
              </div>
            </div>
            <%= f.input :load_address, label: I18n.t('loading_address'), placeholder: I18n.t('full_address') %>

            <div class="row">
              <div class="col-6" >
                <%= f.input :load_date, as: :string, placeholder: I18n.t('load_date'), html5: true, label: I18n.t('load_date'), input_html: {class: "datepicker"} %>
              </div>
              <div class="col-6">
                <%= f.input :load_time, as: :time, html5: true, input_html: {style: "height: 2.25rem"}, label: I18n.t('load_time') %>
              </div>
            </div>

          </div>
          <div class="col-lg-6">
            <div class="row">
              <div class="col-6">
                <%= f.input :unload_c, label: I18n.t('unload'), input_html: { class: 'select2' }, prompt: I18n.t('country'), collection: @countries %>
              </div>
              <div class="col-6">
                <%= f.input :unload_city, label: I18n.t('city'), placeholder: I18n.t('zip_and_place') %>
              </div>
            </div>
            <%= f.input :unload_address, label: I18n.t('unload_address'), placeholder: I18n.t('full_address') %>
            <div class="row">
              <div class="col-6">
                <%= f.input :unload_date, as: :string, input_html: {class: "datepicker"}, placeholder: I18n.t('unload_date'),  html5: true, label: I18n.t('unload_date') %>
              </div>
              <div class="col-6">
                <%= f.input :unload_time, as: :time, html5: true, input_html: {style: "height: 2.25rem"}, label: I18n.t('unload_time') %>
              </div>
            </div>

          </div>
        </div>

        <div class="row">
          <div class="col-4">
            <%= f.input :weight, label: I18n.t('weight'), placeholder: "tons" %>
          </div>
          <div class="col-4">
            <%= f.input :length, label: I18n.t('length'), placeholder: "meters" %>
          </div>
          <div class="col-4">
            <%= f.input :price, label: I18n.t('price'), placeholder: "eur" %>
          </div>
        </div>
          <%= f.input :truck_type, label: I18n.t('truck_type'), prompt: I18n.t('truck_type'), input_html: { class: "tag-selector" },
            item_wrapper_class: 'tag-item', as: :check_boxes, collection: ["Tautliner", "Tandem", "Mega", "Frigo", "Platform", "Combi", "Truck (under 7.5t)", "ADR"] %>
        <%= f.input :description, label: I18n.t('description'), placeholder: I18n.t('more_details') %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, I18n.t('create'), class: "btn btn-primary text-white w-100" %>
      </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <div class="container">
    <p class="text-center m-0"><%= notice %></div>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <div class="container">
    <p class="text-center m-0"><%= alert %></p>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="fixed-bottom text-center my-5">
  <p class="text-muted">Made with <i class="fa text-danger fa-solid fa-heart"></i> in Macedonia</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm <% if !current_page?(root_path) %> bg-white <% end %> navbar-lewagon">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "logoo.png", class: "m-0 rounded-2" %>
      <h5 class= "mx-2 my-0"><strong>cargster</strong></h5>
    <% end %>
    <% if !current_page?(root_path) %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% elsif !user_signed_in? %>
      <%= link_to I18n.t('login'), new_user_session_path, class: " text-muted d-lg-none my-2 mx-2" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-item m-2 active">
          <% if current_page?(root_path) %>
          <%= link_to I18n.t('home'), root_path, class: "nav-link text-truncate text-black text-center" %>
          <% else %>
          <%= link_to I18n.t('home'), root_path, class: "nav-link text-truncate text-center" %>
          <% end %>
        </li>
        <li class="nav-item m-2">
          <% if current_page?(posts_path) %>
          <%= link_to I18n.t('freight_overview'), posts_path, class: "nav-link text-truncate text-black text-center" %>
          <% else %>
          <%= link_to I18n.t('freight_overview'), posts_path, class: "nav-link text-truncate text-center" %>
          <% end %>
        </li>
        <li class="nav-item m-2">
          <% if current_page?(myposts_path) %>
          <%= link_to I18n.t('my_posts'), myposts_path, class: "nav-link text-truncate text-black text-center" %>
          <% else %>
          <%= link_to I18n.t('my_posts'), myposts_path, class: "nav-link text-truncate text-center" %>
          <% end %>
        </li>
        <li class="nav-item m-2">
          <% if current_page?(profile_path) %>
          <%= link_to I18n.t('account'), profile_path, class: "nav-link text-truncate text-black text-center" %>
          <% else %>
          <%= link_to I18n.t('account'), profile_path, class: "nav-link text-truncate text-center" %>
          <% end %>
        </li>
        <li class="nav-item my-2" style="margin-left: 0">
          <% if !current_page?(new_post_path) %>

            <%= link_to I18n.t('create_new'), new_post_path, class: "btn btn-outline-primary w-100 text-nowrap"%>
          <% end %>
        </li>
        <% else %>
        <li class="nav-item m-2 active">
          <%= link_to I18n.t('login'), new_user_session_path, class: "nav-link text-truncate text-center" %>
        </li>

        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_post.html.erb
<div class=" p-4 mb-3 rounded bg-white" style="margin: 0.125rem 0;">

  <div class="row gx-5 gy-3">

    <div class="col-sm-5">
      <div class="d-flex align-items-center justify-content-between">
        <div>
          <p class="m-0 text-nowrap w-50" >
          <span class="fi fi-<%= post.load_c.first(2).downcase %>">
          </span>
          <%= post.load_c.first(2) %>
          <%= post.load_city %>
          </p>
        </div>
        <p class="m-0"><i class="fa fa-sm fa-thin fa-arrow-right"></i></p>
        <div>
          <p class="m-0 text-nowrap text-end w-50" ><%= post.unload_c.first(2) %> <%= post.unload_city %> <span class="fi fi-<%= post.unload_c.first(2).downcase %>"></span></p>
        </div>
      </div>
    </div>

    <div class="col-sm-3">
      <div class="d-flex align-items-center justify-content-between">

        <div>
          <p class="m-0 text-nowrap" >
            <% if current_page?(posts_path) %>
            <i class="fa fa-sm fa-solid fa-user"></i>
            <%= post.user.first_name %>
            <%= post.user.last_name[0] %>.
            <% else %>
              <% if post.status? %>
              <i class="fa fa-sm text-primary fa-solid fa-circle"></i>
              <span class="text-primary"><%= t('status-active') %></span>
              <% else %>
              <i class="fa fa-sm text-danger fa-solid fa-circle"></i>
              <span class="text-danger"><%= t('status-solved') %></span>
              <% end %>
            <% end %>
          </p>
        </div>

        <div>
          <p class="m-0 text-nowrap" >
            <%= post.load_date.try(:strftime, ("%d %b")) %>
            <i class="fa fa-sm fa-solid fa-calendar"></i>
        </div>

      </div>
    </div>

    <div class="col-sm-4">
      <div class="d-flex align-items-center justify-content-between">
        <p class="m-0 text-nowrap text-truncate overflow-auto" style="padding-right: 1rem;"><i class="fa fa-sm fa-solid fa-truck"></i> <%= post.truck_type.drop(1).join(", ") %></p>
        <p class="m-0 text-nowrap text-end" >
        <%= post.length %>m
        <i class="fa fa-sm fa-solid fa-box-open"></i>
      </div>
    </div>

  </div>

</div>

app/views/shared/_switch_locale.html.erb
<div class="m-5 text-center">
<% if I18n.locale == :en %>
<%= link_to url_for(locale: :rs), class: "" do %>
  <p class="m-0">
    <i class="fa fa-solid fa-globe fa"></i> Na Srpski
  </p>
<% end %>
<% else %>
<%= link_to url_for(locale: nil), class: "" do %>
  <p class="m-0">
    <i class="fa fa-solid fa-globe fa"></i> English
  </p>
<% end %>
<% end %>
</div>